import LegalPage from './LegalPage'

export default function PrivacyPolicyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="July 25, 2026">
      <p className="legal__note">
        This policy is a general-purpose template drafted for NotaryHost's actual services and
        data flows. It is not legal advice — have it reviewed by an attorney before treating it
        as final, especially regarding notary-specific and cross-border data rules in your
        jurisdiction.
      </p>

      <>
        <h2>1. Who this applies to</h2>
        <p>
          This Privacy Policy covers NotaryHost (&ldquo;NotaryHost,&rdquo; &ldquo;we,&rdquo;
          &ldquo;us&rdquo;) — the platform at notaryhost.com that provides notaries with a
          website, online booking system, admin dashboard, and phone robot (IVR). It applies to
          notaries who use NotaryHost (&ldquo;Notary Customers&rdquo;) and to the website itself.
          Each Notary Customer&apos;s own subdomain (for example, a site like
          notarygarcia.notaryhost.com) has its own privacy policy covering that notary&apos;s
          end clients, since that notary controls the appointments and communications happening
          there.
        </p>

        <h2>2. Information we collect</h2>
        <p>From Notary Customers, when they sign up and use the platform:</p>
        <ul>
          <li>Business name, owner name, phone number, and email address</li>
          <li>Business address and subdomain/site content you provide</li>
          <li>Login credentials and authentication data (phone number + email, verified by code)</li>
          <li>Billing information, processed by our payment provider (see Section 4)</li>
          <li>
            Operational data generated by your business through the platform — appointments,
            call/consultation records, and message logs
          </li>
        </ul>

        <h2>3. How we use this information</h2>
        <ul>
          <li>To provide, operate, and maintain your notary website, booking system, and phone robot</li>
          <li>To authenticate you when you log into your dashboard</li>
          <li>To send you account, billing, and service notifications</li>
          <li>To bill you for your subscription and any usage-based fees</li>
          <li>To respond to support requests and improve the platform</li>
        </ul>

        <h2>4. How we share information</h2>
        <p>
          We don&apos;t sell your data. We share it with the service providers that power
          NotaryHost, strictly to deliver the service:
        </p>
        <ul>
          <li><strong>Google Firebase / Google Cloud</strong> — hosting, authentication, and database storage</li>
          <li><strong>Twilio</strong> — SMS text messages and phone calls (booking confirmations, reminders, the phone robot)</li>
          <li><strong>Resend</strong> — transactional email (login codes, notifications)</li>
          <li><strong>Stripe</strong> — payment processing for subscriptions, if and when billing is active on your account</li>
        </ul>
        <p>
          We may also disclose information if required by law, or to protect the rights, safety,
          or property of NotaryHost, our customers, or the public.
        </p>

        <h2>5. Data retention</h2>
        <p>
          We retain account and operational data for as long as your subscription is active, and
          for a reasonable period afterward to comply with legal, tax, or accounting
          requirements. You can request deletion of your account data as described in Section 7.
        </p>

        <h2>6. Security</h2>
        <p>
          We use industry-standard safeguards — encrypted connections, access controls, and
          least-privilege service accounts — to protect your data. No system is 100% secure, and
          we can&apos;t guarantee absolute security.
        </p>

        <h2>7. Your rights</h2>
        <p>
          You can request access to, correction of, or deletion of your account data by
          contacting us at the email below. We&apos;ll respond within a reasonable time and
          consistent with applicable law.
        </p>

        <h2>8. Children&apos;s privacy</h2>
        <p>
          NotaryHost is a business-to-business service intended for licensed notaries and is not
          directed at children. We do not knowingly collect information from anyone under 13.
        </p>

        <h2>9. Changes to this policy</h2>
        <p>
          We may update this policy from time to time. We&apos;ll post the revised version here
          with an updated date at the top.
        </p>

        <h2>10. Contact</h2>
        <p>
          Questions about this policy? Email{' '}
          <a href="mailto:yoyoprola@gmail.com">yoyoprola@gmail.com</a>.
        </p>
      </>
    </LegalPage>
  )
}
